[package]
name = "Fibers"
version = "0.1.0"
edition = "2021"
description = "Library for Fibers for owlOS"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
