name: owlOS Developer Builds (AMD64)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
    - name: Grab Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y nasm
    - name: Build owlOS
      run: ./build.py build AMD64 NewWorldPC
    - name: Upload ISO as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: owlOS
        path: ./owlOS.iso
